/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videostoreapp;

/**
 *
 * @author Declan Barnes & Alan Sullivan
 */
public class VideoGUI extends javax.swing.JFrame {

    IStore q;

    /**
     * Creates new form carGUI
     */
    public VideoGUI() {
        initComponents();
        q = new myQueue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        messageTF = new javax.swing.JTextField();
        rentLbl = new javax.swing.JLabel();
        rentTF = new javax.swing.JTextField();
        memberBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 0, 0));
        titleLbl.setText("Video Store");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(130, 10, 290, 44);

        nameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameLbl.setText("Customer Name :");
        getContentPane().add(nameLbl);
        nameLbl.setBounds(20, 70, 140, 14);

        idLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLbl.setForeground(new java.awt.Color(255, 255, 255));
        idLbl.setText("Membership No:");
        getContentPane().add(idLbl);
        idLbl.setBounds(20, 100, 130, 17);
        getContentPane().add(nameTF);
        nameTF.setBounds(160, 68, 150, 20);
        getContentPane().add(idTF);
        idTF.setBounds(160, 102, 57, 20);

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 440, 96);

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(380, 70, 90, 23);

        ViewBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn);
        ViewBtn.setBounds(380, 100, 90, 23);

        messageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTFActionPerformed(evt);
            }
        });
        getContentPane().add(messageTF);
        messageTF.setBounds(20, 300, 450, 20);

        rentLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentLbl.setForeground(new java.awt.Color(255, 255, 255));
        rentLbl.setText("Dvd rented:");
        getContentPane().add(rentLbl);
        rentLbl.setBounds(20, 130, 119, 17);
        getContentPane().add(rentTF);
        rentTF.setBounds(160, 130, 150, 20);

        memberBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        memberBtn.setText("Search ");
        memberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBtnActionPerformed(evt);
            }
        });
        getContentPane().add(memberBtn);
        memberBtn.setBounds(223, 101, 90, 23);

        removeBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBtn);
        removeBtn.setBounds(380, 130, 90, 23);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        backgroundLbl.setMaximumSize(new java.awt.Dimension(500, 500));
        backgroundLbl.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 480, 360);

        setSize(new java.awt.Dimension(496, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String tmp = "[Customer Name]:" + " " + nameTF.getText() + "  -  " + "[Membership No]:" + " " + idTF.getText()+ "  -  "+"[Dvd rented]:" + " " + rentTF.getText();

        q.enqueue(tmp);

        nameTF.setText("");
        idTF.setText("");
        rentTF.setText("");

        displayTA.setText("-- Transaction Completed! --");

    }//GEN-LAST:event_addBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        displayTA.setText(q.display());

        if (q.isEmpty()) {
            messageTF.setText("[ERROR]:No data has been entered!");
        }
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void messageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTFActionPerformed

    private void memberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBtnActionPerformed
        // TODO add your handling code here:
         String tmp = q.display();
        String member = idTF.getText();
        
        if (q.isEmpty()) {
            messageTF.setText("[No Members!]");
        } else if (tmp.contains(member)) {
            messageTF.setText("Customer with Membership No:"+member+ " " + ", is a valid member !");
        } else if (member.equals("")) {
            messageTF.setText("[ERROR!][You have not entered a number!]");
        } else {
            messageTF.setText("Not a member!");
        }
    }//GEN-LAST:event_memberBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        String tmp = (String) q.dequeue();
        displayTA.setText(q.display());

        if (q.isEmpty()) {
            messageTF.setText("Dvd returned");
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton memberBtn;
    private javax.swing.JTextField messageTF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel rentLbl;
    private javax.swing.JTextField rentTF;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

    
}
